name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Setup Nodejs
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Pnpm install
        run: pnpm install --frozen-lockfile

      - name: Create env file
        run: |
          touch .env
          echo DB_HOST="${{ secrets.DB_HOST_LAO }}" >> .env
          echo DB_PASSWORD="${{ secrets.DB_PASSWORD_LAO }}" >> .env
          echo JWT_SIGN_KEY="${{ secrets.JWT_SIGN_KEY }}" >> .env
          cat .env

      - name: Serverless deploy
        run: npm run deploy
